### ISSUE TITLE
Caused by: java.lang.NullPointerException at br.liveo.navigationliveo.NavigationLiveo.onCreate(SourceFile:113)

### ISSUE THREAD

**Issue by NickDaKing** [rudsonlive/NavigationDrawer-MaterialDesign#70]
I receive a NPE on many android devices my app is running. 

        java.lang.RuntimeException: Unable to start activity ComponentInfo{net.iaskapp.iask/net.iaskapp.iask.MainActivity}: java.lang.NullPointerException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2262)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2316)
        at android.app.ActivityThread.access$700(ActivityThread.java:158)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1296)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:5365)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
        at dalvik.system.NativeStart.main(Native Method)
        Caused by: java.lang.NullPointerException
        at net.iaskapp.iask.util.NavigationLiveo.onCreate(SourceFile:113)
        at android.app.Activity.performCreate(Activity.java:5326)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2225)
        ... 11 more
        java.lang.NullPointerException
        at net.iaskapp.iask.util.NavigationLiveo.onCreate(SourceFile:113)
        at android.app.Activity.performCreate(Activity.java:5326)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2225)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2316)
        at android.app.ActivityThread.access$700(ActivityThread.java:158)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1296)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:5365)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by umohi** [comment]
@NickDaKing  did you ever find a solution to this issue?

**Comment by rudsonlive** [comment]
This is happening in the latest version of the library?

**Comment by johngamarra** [comment]
Using latest version 2.3.5


10-03 11:20:50.156 9258-9258/co.igestion.igestion E/AndroidRuntime:  Caused by: java.lang.NullPointerException
10-03 11:20:50.156 9258-9258/co.igestion.igestion E/AndroidRuntime:     at br.liveo.navigationliveo.NavigationLiveo.onCreate(NavigationLiveo.java:118)
10-03 11:20:50.156 9258-9258/co.igestion.igestion E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:5426)
10-03 11:20:50.156 9258-9258/co.igestion.igestion E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
10-03 11:20:50.156 9258-9258/co.igestion.igestion E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2269)
10-03 11:20:50.156 9258-9258/co.igestion.igestion E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2363) 
10-03 11:20:50.156 9258-9258/co.igestion.igestion E/AndroidRuntime:     at android.app.ActivityThread.access$900(ActivityThread.java:161) 
10-03 11:20:50.156 9258-9258/co.igestion.igestion E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265) 
10-03 11:20:50.156 9258-9258/co.igestion.igestion E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
10-03 11:20:50.156 9258-9258/co.igestion.igestion E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:157) 
10-03 11:20:50.156 9258-9258/co.igestion.igestion E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5356) 
10-03 11:20:50.156 9258-9258/co.igestion.igestion E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
10-03 11:20:50.156 9258-9258/co.igestion.igestion E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515) 
10-03 11:20:50.156 9258-9258/co.igestion.igestion E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265) 
10-03 11:20:50.156 9258-9258/co.igestion.igestion E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081) 
10-03 11:20:50.156 9258-9258/co.igestion.igestion E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)

**Comment by johngamarra** [comment]
I'm getting this error on 2.3.4 also, probably has something to do with new Android support library 23.0.1

**Comment by rudsonlive** [comment]
You are with your updated SDK?

**Comment by johngamarra** [comment]
minSdkVersion 14
        targetSdkVersion 23

**Comment by johngamarra** [comment]
any solution? this is blocking my app

**Comment by rudsonlive** [comment]
I can not simulate your situation.

I have created a project from scratch and added the library and works without problem.

Try to tell me more details, send me imagems of your code, show me you study using the library.

Style.xml your file is OK?

**Comment by johngamarra** [comment]
@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
        mountListNavigation(savedInstanceState);

        if (savedInstanceState != null) {
            isSaveInstance = true;
            setCurrentPosition(savedInstanceState.getInt(CURRENT_POSITION));
        }

        if (savedInstanceState == null) {
            mOnItemClickLiveo.onItemClick(mCurrentPosition);
        }

        setCheckedItemNavigation(mCurrentPosition, true);
	}

NPE is in line mOnItemClickLiveo.onItemClick(mCurrentPosition);

**Comment by johngamarra** [comment]
nvm it was my problem sorry

**Comment by rudsonlive** [comment]
Friend is not using the wrong library.
You must add the compile your project and use what the library offers.

See how it is used in this sample project.
NavigationDrawerViewPage-MaterialDesign
<https://github.com/rudsonlive/NavigationDrawerViewPage-MaterialDesign>

2015-10-06 12:41 GMT-03:00 John Gamarra <notifications@github.com>:

> @Override
> protected void onCreate(Bundle savedInstanceState) {
>     super.onCreate(savedInstanceState);
>     mountListNavigation(savedInstanceState);
>
>     if (savedInstanceState != null) {
>         isSaveInstance = true;
>         setCurrentPosition(savedInstanceState.getInt(CURRENT_POSITION));
>     }
>
>     if (savedInstanceState == null) {
>         mOnItemClickLiveo.onItemClick(mCurrentPosition);
>     }
>
>     setCheckedItemNavigation(mCurrentPosition, true);
> }
>
> NPE is in line mOnItemClickLiveo.onItemClick(mCurrentPosition);
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/70#issuecomment-145904719>
> .
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>

**Comment by manumathew17** [comment]
Getting error on some Vivo models
Trace from play console

java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3740)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3898)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:85)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2305)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:257)
  at android.app.ActivityThread.main (ActivityThread.java:8192)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:626)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1015)
Caused by: java.lang.NullPointerException: 
  at br.liveo.navigationliveo.NavigationLiveo.onCreate (NavigationLiveo.java:120)
  at android.app.Activity.performCreate (Activity.java:8119)
  at android.app.Activity.performCreate (Activity.java:8103)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1359)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3713)
